//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiNextSoft.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class banconextsoftEntities1 : DbContext
    {
        public banconextsoftEntities1()
            : base("name=banconextsoftEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<ENDERECOS> ENDERECOS { get; set; }
        public virtual DbSet<CIDADES> CIDADES { get; set; }
        public virtual DbSet<ESTADOS> ESTADOS { get; set; }
    }
}
